apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: izio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: izio
    app.kubernetes.io/part-of: byoc-app-hbje
  name: izioxd7j
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: izio
    weight: null
status: {}
